
-----------------------------------------------------
local PLUGIN = PLUGIN;

PLUGIN.voices = Clockwork.kernel:NewLibrary("CitizenVoices");

PLUGIN.voices.stored = {
	citizenVoices = {}
};

-- A function to add a citizen voice.
function PLUGIN.voices:AddCitizen(faction, command, phrase, sound, female, menu)
	self.stored.citizenVoices[#self.stored.citizenVoices + 1] = {
		command = command,
		faction = faction,
		phrase = phrase,
		female = female,
		sound = sound,
		menu = menu
	};
end;

-- Citizen = Directory
PLUGIN.voices:AddCitizen("Citizen", "You all over", "That's you all over.", "vo/npc/male01/answer01.wav", "vo/npc/female01/answer01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hold it against you", "I won't hold it against you.", "vo/npc/male01/answer02.wav", "vo/npc/female01/answer02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Figures", "Figures.", "vo/npc/male01/answer03.wav", "vo/npc/female01/answer03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dwell on it", "Try not to dwell on it.", "vo/npc/male01/answer04.wav", "vo/npc/female01/answer04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Talk later", "Can we talk about this later?", "vo/npc/male01/answer05.wav", "vo/npc/female01/answer05.wav");
PLUGIN.voices:AddCitizen("Citizen", "Same here", "Same here.", "vo/npc/male01/answer07.wav", "vo/npc/female01/answer07.wav");
PLUGIN.voices:AddCitizen("Citizen", "Know what you mean", "Know what you mean.", "vo/npc/male01/answer08.wav", "vo/npc/female01/answer08.wav");
PLUGIN.voices:AddCitizen("Citizen", "Talking to yourself", "Talking to yourself again.", "vo/npc/male01/answer09.wav", "vo/npc/female01/answer09.wav");
PLUGIN.voices:AddCitizen("Citizen", "Say that too loud", "I wouldn't say that too loud.", "vo/npc/male01/answer10.wav", "vo/npc/female01/answer10.wav");
PLUGIN.voices:AddCitizen("Citizen", "Tomb stone", "I'll put it on your tomb stone.", "vo/npc/male01/answer11.wav", "vo/npc/female01/answer11.wav");
PLUGIN.voices:AddCitizen("Citizen", "Thinking about", "Doesn't bare thinking about.", "vo/npc/male01/answer12.wav", "vo/npc/female01/answer12.wav");
PLUGIN.voices:AddCitizen("Citizen", "With you", "I'm with you.", "vo/npc/male01/answer13.wav", "vo/npc/female01/answer13.wav");
PLUGIN.voices:AddCitizen("Citizen", "You and me both", "You and me both.", "vo/npc/male01/answer14.wav", "vo/npc/female01/answer14.wav");
PLUGIN.voices:AddCitizen("Citizen", "looking at it", "That's one way of looking at it.", "vo/npc/male01/answer15.wav", "vo/npc/female01/answer15.wav");
PLUGIN.voices:AddCitizen("Citizen", "Original Thought", "Have you ever had an original thought?", "vo/npc/male01/answer16.wav", "vo/npc/female01/answer16.wav");
PLUGIN.voices:AddCitizen("Citizen", "Shut up", "I'm not even going to tell you to shut up.", "vo/npc/male01/answer17.wav", "vo/npc/female01/answer17.wav");
PLUGIN.voices:AddCitizen("Citizen", "Task at hand", "Let's concentrate on the task at hand.", "vo/npc/male01/answer18.wav", "vo/npc/female01/answer18.wav");
PLUGIN.voices:AddCitizen("Citizen", "Mind on work", "Keep your mind on your work.", "vo/npc/male01/answer19.wav", "vo/npc/female01/answer19.wav");
PLUGIN.voices:AddCitizen("Citizen", "Mind in gutter", "Your mind is in the gutter.", "vo/npc/male01/answer20.wav", "vo/npc/female01/answer20.wav");
PLUGIN.voices:AddCitizen("Citizen", "Sure of that", "Don't be so sure of that.", "vo/npc/male01/answer21.wav", "vo/npc/female01/answer21.wav");
PLUGIN.voices:AddCitizen("Citizen", "Never know", "You never know.", "vo/npc/male01/answer22.wav", "vo/npc/female01/answer22.wav");
PLUGIN.voices:AddCitizen("Citizen", "Never can tell", "Never can tell.", "vo/npc/male01/answer23.wav", "vo/npc/female01/answer23.wav");
PLUGIN.voices:AddCitizen("Citizen", "Why telling me", "Why are you telling me?", "vo/npc/male01/answer24.wav", "vo/npc/female01/answer24.wav");
PLUGIN.voices:AddCitizen("Citizen", "How about that", "How about that.", "vo/npc/male01/answer25.wav", "vo/npc/female01/answer25.wav");
PLUGIN.voices:AddCitizen("Citizen", "More information", "That's more information than I require.", "vo/npc/male01/answer26.wav", "vo/npc/female01/answer26.wav");
PLUGIN.voices:AddCitizen("Citizen", "Wannna bet", "Wanna bet?", "vo/npc/male01/answer27.wav", "vo/npc/female01/answer27.wav");
PLUGIN.voices:AddCitizen("Citizen", "A dime", "I wish I had a dime for everytime somebody said that.", "vo/npc/male01/answer28.wav", "vo/npc/female01/answer28.wav");
PLUGIN.voices:AddCitizen("Citizen", "Do about it", "What am I supposed to do about it?", "vo/npc/male01/answer29.wav", "vo/npc/female01/answer29.wav");
PLUGIN.voices:AddCitizen("Citizen", "Talking to me", "You talking to me?", "vo/npc/male01/answer30.wav", "vo/npc/female01/answer30.wav");
PLUGIN.voices:AddCitizen("Citizen", "Nip that talk", "You should nip that kind of talk in the bud.", "vo/npc/male01/answer31.wav", "vo/npc/female01/answer31.wav");
PLUGIN.voices:AddCitizen("Citizen", "Right on", "Right on.", "vo/npc/male01/answer32.wav", "vo/npc/female01/answer32.wav");
PLUGIN.voices:AddCitizen("Citizen", "No argument", "No argument there.", "vo/npc/male01/answer33.wav", "vo/npc/female01/answer33.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hawaii", "Don't forget hawaii.", "vo/npc/male01/answer34.wav", "vo/npc/female01/answer34.wav");
PLUGIN.voices:AddCitizen("Citizen", "Let it get to you", "Try not to let it get to you.", "vo/npc/male01/answer35.wav", "vo/npc/female01/answer36.wav");
PLUGIN.voices:AddCitizen("Citizen", "First time", "Wouldn't be the first time.", "vo/npc/male01/answer36.wav", "vo/npc/female01/answer37.wav");
PLUGIN.voices:AddCitizen("Citizen", "Sure about that", "You sure about that?", "vo/npc/male01/answer37.wav", "vo/npc/female01/answer38.wav");
PLUGIN.voices:AddCitizen("Citizen", "Leave it alone", "Leave it alone.", "vo/npc/male01/answer38.wav", "vo/npc/female01/answer39.wav");
PLUGIN.voices:AddCitizen("Citizen", "Enough out of you", "That's enough out of you.", "vo/npc/male01/answer39.wav", "vo/npc/female01/answer40.wav");
PLUGIN.voices:AddCitizen("Citizen", "Talking to me", "You talking to me?", "vo/npc/male01/answer30.wav", "vo/npc/female01/answer30.wav");
PLUGIN.voices:AddCitizen("Citizen", "Remember anything", "I can't remember the last time I had, well... Anything.", "vo/npc/male01/question31.wav", "vo/npc/female01/answer35.wav");
PLUGIN.voices:AddCitizen("Citizen", "Wars gonna end", "I don't think this wars ever gonna end.", "vo/npc/male01/question01.wav", "vo/npc/female01/question01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Sell insurance", "To think, all I used to wanna do is sell insurance.", "vo/npc/male01/question02.wav", "vo/npc/female01/question02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dream anymore", "I don't dream anymore.", "vo/npc/male01/question03.wav", "vo/npc/female01/question03.wav");
PLUGIN.voices:AddCitizen("Citizen", "All over kidding", "When this is all over I'm... Ah who am I kidding.", "vo/npc/male01/question04.wav", "vo/npc/female01/question04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Deja vu", "Woah, Deja vu.", "vo/npc/male01/question05.wav", "vo/npc/female01/question05.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dream about cheese", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav", "vo/npc/female01/question06.wav");
PLUGIN.voices:AddCitizen("Citizen", "Smell freedom", "You smell that? It's freedom.", "vo/npc/male01/question07.wav", "vo/npc/female01/question07.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hands on doctor breen", "If I ever get my hands on Doctor Breen.", "vo/npc/male01/question08.wav", "vo/npc/female01/question08.wav");
PLUGIN.voices:AddCitizen("Citizen", "Eat a horse", "I could eat a horse, hooves and all.", "vo/npc/male01/question09.wav", "vo/npc/female01/question09.wav");
PLUGIN.voices:AddCitizen("Citizen", "Day finally come", "I can't believe this day has finally come.", "vo/npc/male01/question10.wav", "vo/npc/female01/question10.wav");
PLUGIN.voices:AddCitizen("Citizen", "Not part of plan", "I'm pretty sure this isn't part of the plan.", "vo/npc/male01/question11.wav", "vo/npc/female01/question11.wav");
PLUGIN.voices:AddCitizen("Citizen", "Getting worse", "Looks to me things are getting worse, not better.", "vo/npc/male01/question12.wav", "vo/npc/female01/question12.wav");
PLUGIN.voices:AddCitizen("Citizen", "Live my life over", "If I could live my life over again.", "vo/npc/male01/question13.wav", "vo/npc/female01/question13.wav");
PLUGIN.voices:AddCitizen("Citizen", "Reminds me of", "I'm not even going to tell you what that reminds me of.", "vo/npc/male01/question14.wav", "vo/npc/female01/question14.wav");
PLUGIN.voices:AddCitizen("Citizen", "Stalker out of me", "They're never going to make a stalker out of me.", "vo/npc/male01/question15.wav", "vo/npc/female01/question15.wav");
PLUGIN.voices:AddCitizen("Citizen", "Change in air", "Finally, change is in the air.", "vo/npc/male01/question16.wav", "vo/npc/female01/question16.wav");
PLUGIN.voices:AddCitizen("Citizen", "You feel it", "You feel it? I feel it.", "vo/npc/male01/question17.wav", "vo/npc/female01/question17.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dont feel anything", "I don't feel anything anymore.", "vo/npc/male01/question18.wav", "vo/npc/female01/question18.wav");
PLUGIN.voices:AddCitizen("Citizen", "Last shower", "I can't remember the last time I had a shower.", "vo/npc/male01/question19.wav", "vo/npc/female01/question19.wav");
PLUGIN.voices:AddCitizen("Citizen", "Bad memory", "Someday, this will all be a bad memory.", "vo/npc/male01/question20.wav", "vo/npc/female01/question20.wav");
PLUGIN.voices:AddCitizen("Citizen", "Betting man", "I'm not a betting man, but the odds are not good.", "vo/npc/male01/question21.wav", "vo/npc/female01/question21.wav");
PLUGIN.voices:AddCitizen("Citizen", "Care what i think", "Doesn't anyone care what I think?", "vo/npc/male01/question22.wav", "vo/npc/female01/question22.wav");
PLUGIN.voices:AddCitizen("Citizen", "Whistle tune", "I can't get this tune out of my head. *Whistling*", "vo/npc/male01/question23.wav", "vo/npc/female01/question23.wav");
PLUGIN.voices:AddCitizen("Citizen", "One of those days", "I just knew it was going to be one of those days.", "vo/npc/male01/question25.wav", "vo/npc/female01/question25.wav");
PLUGIN.voices:AddCitizen("Citizen", "Bullshit", "This is bullshit!", "vo/npc/male01/question26.wav", "vo/npc/female01/question26.wav");
PLUGIN.voices:AddCitizen("Citizen", "Ate something bad", "I think I ate something bad.", "vo/npc/male01/question27.wav", "vo/npc/female01/question27.wav");
PLUGIN.voices:AddCitizen("Citizen", "Im hungry", "God I'm hungry.", "vo/npc/male01/question28.wav", "vo/npc/female01/question28.wav");
PLUGIN.voices:AddCitizen("Citizen", "Gonna mate", "When this is all over, I'm gonna mate.", "vo/npc/male01/question29.wav", "vo/npc/female01/question29.wav");
PLUGIN.voices:AddCitizen("Citizen", "No kids", "I'm glad there's no kids around to see this.", "vo/npc/male01/question30.wav", "vo/npc/female01/question30.wav");
PLUGIN.voices:AddCitizen("Citizen", "Behind you", "Behind you!", "vo/npc/male01/behindyou01.wav", "vo/npc/female01/behindyou01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Im busy", "Can't you see I'm busy?", "vo/npc/male01/busy02.wav", "vo/npc/female01/busy02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Look out below", "Look out below!", "vo/npc/male01/cit_dropper04.wav", "vo/npc/female01/cit_dropper04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Civil protection", "Civil protection!", "vo/npc/male01/civilprotection01.wav", "vo/npc/female01/civilprotection01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Combine", "Combine!", "vo/npc/male01/combine01.wav", "vo/npc/female01/combine01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Cps", "Cps!", "vo/npc/male01/cps01.wav", "vo/npc/female01/cps01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Cover reload", "Cover me while I reload.", "vo/npc/male01/coverwhilereload01.wav", "vo/npc/female01/coverwhilereload01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Doing something", "Shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav", "vo/npc/female01/doingsomething.wav");
PLUGIN.voices:AddCitizen("Citizen", "Excuse me", "Excuse me.", "vo/npc/male01/excuseme01.wav", "vo/npc/female01/excuseme01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Fantastic", "Fantastic!", "vo/npc/male01/fantastic01.wav", "vo/npc/female01/fantastic01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Finally", "Finally.", "vo/npc/male01/finally.wav", "vo/npc/female01/finally.wav");
PLUGIN.voices:AddCitizen("Citizen", "Get down", "Get down!", "vo/npc/male01/getdown02.wav", "vo/npc/female01/getdown02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Get going soon", "Are we gonna get going soon?", "vo/npc/male01/getgoingsoon.wav", "vo/npc/female01/getgoingsoon.wav");
PLUGIN.voices:AddCitizen("Citizen", "Get the hell out", "Get the hell out of here!", "vo/npc/male01/gethellout.wav", "vo/npc/female01/gethellout.wav");
PLUGIN.voices:AddCitizen("Citizen", "Good god", "Good god.", "vo/npc/male01/goodgod.wav", "vo/npc/female01/goodgod.wav");
PLUGIN.voices:AddCitizen("Citizen", "Now what", "Now what.", "vo/npc/male01/gordead_ans01.wav", "vo/npc/female01/gordead_ans01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Going so well", "And things were going so well.", "vo/npc/male01/gordead_ans02.wav", "vo/npc/female01/gordead_ans02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dont tell me", "Don't tell me.", "vo/npc/male01/gordead_ans03.wav", "vo/npc/female01/gordead_ans03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Oh god", "Oh god.", "vo/npc/male01/gordead_ans04.wav", "vo/npc/female01/gordead_ans04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Oh no", "Oh no.", "vo/npc/male01/gordead_ans05.wav", "vo/npc/female01/gordead_ans05.wav");
PLUGIN.voices:AddCitizen("Citizen", "Please no", "Please no!", "vo/npc/male01/gordead_ans06.wav", "vo/npc/female01/gordead_ans06.wav");
PLUGIN.voices:AddCitizen("Citizen", "Thats gotta hurt", "If you dare say... that's gotta hurt, I'll kill you.", "vo/npc/male01/gordead_ans07.wav", "vo/npc/female01/gordead_ans07.wav");
PLUGIN.voices:AddCitizen("Citizen", "Bury him here", "Should we bury him here?", "vo/npc/male01/gordead_ans08.wav", "vo/npc/female01/gordead_ans08.wav");
PLUGIN.voices:AddCitizen("Citizen", "Even he could not help", "I had a feeling even he couldn't help us.", "vo/npc/male01/gordead_ans09.wav", "vo/npc/female01/gordead_ans09.wav");
PLUGIN.voices:AddCitizen("Citizen", "Spread the word", "Spread the word.", "vo/npc/male01/gordead_ans10.wav", "vo/npc/female01/gordead_ans10.wav");
PLUGIN.voices:AddCitizen("Citizen", "What is the use", "What's the use?", "vo/npc/male01/gordead_ans11.wav", "vo/npc/female01/gordead_ans11.wav");
PLUGIN.voices:AddCitizen("Citizen", "What is the point", "What's the point?", "vo/npc/male01/gordead_ans12.wav", "vo/npc/female01/gordead_ans12.wav");
PLUGIN.voices:AddCitizen("Citizen", "Why go on", "Why go on?", "vo/npc/male01/gordead_ans13.wav", "vo/npc/female01/gordead_ans13.wav");
PLUGIN.voices:AddCitizen("Citizen", "Were done for", "We're done for.", "vo/npc/male01/gordead_ans14.wav", "vo/npc/female01/gordead_ans14.wav");
PLUGIN.voices:AddCitizen("Citizen", "Well now what", "Well, now what?", "vo/npc/male01/gordead_ans15.wav", "vo/npc/female01/gordead_ans15.wav");
PLUGIN.voices:AddCitizen("Citizen", "Dibs on the suit", "Dibs on the suit!", "vo/npc/male01/gordead_ans16.wav", "vo/npc/female01/gordead_ans16.wav");
PLUGIN.voices:AddCitizen("Citizen", "Done this before", "He's done this before, he'll be okay.", "vo/npc/male01/gordead_ans18.wav", "vo/npc/female01/gordead_ans18.wav");
PLUGIN.voices:AddCitizen("Citizen", "Gonna be sick", "I'm gonna be sick.", "vo/npc/male01/gordead_ans19.wav", "vo/npc/female01/gordead_ans19.wav");
PLUGIN.voices:AddCitizen("Citizen", "Take his crowbar", "Somebody, take his crowbar.", "vo/npc/male01/gordead_ans20.wav", "vo/npc/female01/gordead_ans20.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hes dead", "He's dead.", "vo/npc/male01/gordead_ques01.wav", "vo/npc/female01/gordead_ques01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Way to go", "What a way to go.", "vo/npc/male01/gordead_ques02.wav", "vo/npc/female01/gordead_ques02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Cant be", "This can't be.", "vo/npc/male01/gordead_ques06.wav", "vo/npc/female01/gordead_ques06.wav");
PLUGIN.voices:AddCitizen("Citizen", "Look hes dead", "Look he's dead.", "vo/npc/male01/gordead_ques07.wav", "vo/npc/female01/gordead_ques07.wav");
PLUGIN.voices:AddCitizen("Citizen", "This is bad", "This, is bad.", "vo/npc/male01/gordead_ques10.wav", "vo/npc/female01/gordead_ques10.wav");
PLUGIN.voices:AddCitizen("Citizen", "End like this", "It's not supposed to end like this.", "vo/npc/male01/gordead_ques14.wav", "vo/npc/female01/gordead_ques14.wav");
PLUGIN.voices:AddCitizen("Citizen", "What now", "What now?", "vo/npc/male01/gordead_ques16.wav", "vo/npc/female01/gordead_ques16.wav");
PLUGIN.voices:AddCitizen("Citizen", "Got one", "Got one!", "vo/npc/male01/gotone01.wav", "vo/npc/female01/gotone01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Gotta reload", "Gotta reload.", "vo/npc/male01/gottareload01.wav", "vo/npc/female01/gottareload01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hacks", "Hacks!", "vo/npc/male01/hacks01.wav", "vo/npc/female01/hacks01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Headcrabs", "Headcrabs!", "vo/npc/male01/headcrabs01.wav", "vo/npc/female01/headcrabs01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Heads up", "Heads up!", "vo/npc/male01/headsup01.wav", "vo/npc/female01/headsup01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Help", "Help!", "vo/npc/male01/help01.wav", "vo/npc/female01/help01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Here come hacks", "Here come the hacks!", "vo/npc/male01/herecomehacks01.wav", "vo/npc/female01/herecomehacks01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Here they come", "Here they come!", "vo/npc/male01/heretheycome01.wav", "vo/npc/female01/heretheycome01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Here to help", "We thought you were here to help.", "vo/npc/male01/heretohelp01.wav", "vo/npc/female01/heretohelp01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hi", "Hi.", "vo/npc/male01/hi01.wav", "vo/npc/female01/hi01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hit in gut", "Aargh, hit in the gut.", "vo/npc/male01/hitingut01.wav", "vo/npc/female01/hitingut01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Hold this spot", "I'm gonna stay here and hold down this spot.", "vo/npc/male01/holddownspot01.wav", "vo/npc/female01/holddownspot01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Ill stay here", "I'll stay here", "vo/npc/male01/illstayhere01.wav", "vo/npc/female01/illstayhere01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Im hurt", "Aargh, I'm hurt.", "vo/npc/male01/imhurt01.wav", "vo/npc/female01/imhurt01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Sticking here", "I'm sticking here.", "vo/npc/male01/imstickinghere01.wav", "vo/npc/female01/imstickinghere01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Incoming", "Incoming!", "vo/npc/male01/incoming02.wav", "vo/npc/female01/incoming02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Lead the way", "You lead the way!", "vo/npc/male01/leadtheway01.wav", "vo/npc/female01/leadtheway01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Lets go", "Lets go.", "vo/npc/male01/letsgo02.wav", "vo/npc/female01/letsgo02.wav");
PLUGIN.voices:AddCitizen("Citizen", "My arm", "Aargh, my arm.", "vo/npc/male01/myarm01.wav", "vo/npc/female01/myarm01.wav");
PLUGIN.voices:AddCitizen("Citizen", "My leg", "Aargh, my leg.", "vo/npc/male01/myleg01.wav", "vo/npc/female01/myleg01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Nice", "Nice!", "vo/npc/male01/nice.wav", "vo/npc/female01/nice02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Noooo", "Nooooo!", "vo/npc/male01/no02.wav", "vo/npc/female01/no02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Man I thought", "You're not the man I thought you were.", "vo/npc/male01/notthemanithought02.wav", "vo/npc/female01/notthemanithought02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Oh no", "Oh no.", "vo/npc/male01/ohno.wav", "vo/npc/female01/ohno.wav");
PLUGIN.voices:AddCitizen("Citizen", "Okay", "Okay!", "vo/npc/male01/ok01.wav", "vo/npc/female01/ok01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Im ready", "Okay, I'm ready.", "vo/npc/male01/okimready01.wav", "vo/npc/female01/okimready01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Get out of way", "Let me get out of your way.", "vo/npc/male01/outofyourway02.wav", "vo/npc/female01/outofyourway02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Over here", "Over here!", "vo/npc/male01/overhere01.wav", "vo/npc/female01/overhere01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Over there", "Over there!", "vo/npc/male01/overthere01.wav", "vo/npc/female01/overthere01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Pardon me", "Pardon me.", "vo/npc/male01/pardonme02.wav", "vo/npc/female01/pardonme02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Ready when you are", "Ready when you are!", "vo/npc/male01/readywhenyouare01.wav", "vo/npc/female01/readywhenyouare01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Run for your life", "Run for your life!", "vo/npc/male01/runforyourlife02.wav", "vo/npc/female01/runforyourlife02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Sorry", "Sorry.", "vo/npc/male01/sorry03.wav", "vo/npc/female01/sorry03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Follow me", "Follow me!", "vo/npc/male01/squad_away03.wav", "vo/npc/female01/squad_away03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Tale cover", "Take cover.", "vo/npc/male01/takecover02.wav", "vo/npc/female01/takecover02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Do nicely", "This will do nicely.", "vo/npc/male01/thislldonicely01.wav", "vo/npc/female01/thislldonicely01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Uh oh", "Uh oh!", "vo/npc/male01/uhoh.wav", "vo/npc/female01/uhoh.wav");
PLUGIN.voices:AddCitizen("Citizen", "Up there", "Up there!", "vo/npc/male01/upthere01.wav", "vo/npc/female01/upthere01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Waiting for somebody", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav", "vo/npc/female01/waitingsomebody.wav");
PLUGIN.voices:AddCitizen("Citizen", "Watch out", "Watch out!", "vo/npc/male01/watchout.wav", "vo/npc/female01/watchout.wav");
PLUGIN.voices:AddCitizen("Citizen", "Watch what doing", "Watch what you're doing!", "vo/npc/male01/watchwhat.wav", "vo/npc/female01/watchwhat.wav");
PLUGIN.voices:AddCitizen("Citizen", "We trusted you", "We trusted you!", "vo/npc/male01/wetrustedyou01.wav", "vo/npc/female01/wetrustedyou01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Woops", "Woops.", "vo/npc/male01/whoops01.wav", "vo/npc/female01/whoops01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Yeah", "Yeah.", "vo/npc/male01/yeah02.wav", "vo/npc/female01/yeah02.wav");
PLUGIN.voices:AddCitizen("Citizen", "You reload", "You'd better reload.", "vo/npc/male01/youdbetterreload01.wav", "vo/npc/female01/youdbetterreload01.wav");
PLUGIN.voices:AddCitizen("Citizen", "You got it", "You got it.", "vo/npc/male01/yougotit02.wav", "vo/npc/female01/yougotit02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Zombies", "Zombies!", "vo/npc/male01/zombies01.wav", "vo/npc/female01/zombies01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Woops", "Woops.", "vo/npc/male01/whoops01.wav", "vo/npc/female01/whoops01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Mumbo jumbo", "Enough of your mumbo jumbo.", "vo/npc/male01/vanswer01.wav", "vo/npc/female01/vanswer01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Damn vorts", "Damn vorts.", "vo/npc/male01/vanswer02.wav", "vo/npc/female01/vanswer02.wav");
PLUGIN.voices:AddCitizen("Citizen", "How to take that", "I'm not sure how to take that.", "vo/npc/male01/vanswer03.wav", "vo/npc/female01/vanswer03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Take that personally", "Should I take that personally?", "vo/npc/male01/vanswer04.wav", "vo/npc/female01/vanswer04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Speak english", "Speak english.", "vo/npc/male01/vanswer05.wav", "vo/npc/female01/vanswer05.wav");
PLUGIN.voices:AddCitizen("Citizen", "Got that from me", "You got that from me!", "vo/npc/male01/vanswer06.wav", "vo/npc/female01/vanswer06.wav");
PLUGIN.voices:AddCitizen("Citizen", "Put up with you", "That's why we put up with you.", "vo/npc/male01/vanswer07.wav", "vo/npc/female01/vanswer07.wav");
PLUGIN.voices:AddCitizen("Citizen", "Put it better myself", "Couldn't have put it better myself.", "vo/npc/male01/vanswer08.wav", "vo/npc/female01/vanswer08.wav");
PLUGIN.voices:AddCitizen("Citizen", "Almost made sense", "That, almost made sense.", "vo/npc/male01/vanswer09.wav", "vo/npc/female01/vanswer09.wav");
PLUGIN.voices:AddCitizen("Citizen", "Something wrong with me", "Something must be wrong with me, I almost understood that.", "vo/npc/male01/vanswer10.wav", "vo/npc/female01/vanswer10.wav");
PLUGIN.voices:AddCitizen("Citizen", "Getting used to vorts", "I guess I'm getting used to you vorts.", "vo/npc/male01/vanswer11.wav", "vo/npc/female01/vanswer11.wav");
PLUGIN.voices:AddCitizen("Citizen", "Vort philosophy", "None of your vort philosophy.", "vo/npc/male01/vanswer12.wav", "vo/npc/female01/vanswer12.wav");
PLUGIN.voices:AddCitizen("Citizen", "Stop killing me", "Stop you're killing me.", "vo/npc/male01/vanswer13.wav", "vo/npc/female01/vanswer13.wav");
PLUGIN.voices:AddCitizen("Citizen", "Do to deserve this", "What did I do to deserve this.", "vo/npc/male01/vanswer14.wav", "vo/npc/female01/vanswer14.wav");
PLUGIN.voices:AddCitizen("Citizen", "Stop looking at me", "Stop looking at me like that.", "vo/npc/male01/vquestion01.wav", "vo/npc/female01/vquestion01.wav");
PLUGIN.voices:AddCitizen("Citizen", "Never get used to", "Some things I just never get used to.", "vo/npc/male01/vquestion02.wav", "vo/npc/female01/vquestion02.wav");
PLUGIN.voices:AddCitizen("Citizen", "Survived this long", "I don't know how you things have survived as long as you have.", "vo/npc/male01/vquestion03.wav", "vo/npc/female01/vquestion03.wav");
PLUGIN.voices:AddCitizen("Citizen", "Ended up with you", "Sometimes I wonder how I ended up with you.", "vo/npc/male01/vquestion04.wav", "vo/npc/female01/vquestion04.wav");
PLUGIN.voices:AddCitizen("Citizen", "Alright vorty", "You're alright vorty.", "vo/npc/male01/vquestion05.wav", "vo/npc/female01/vquestion05.wav");
PLUGIN.voices:AddCitizen("Citizen", "Vorts half bad", "You vorts aren't half bad.", "vo/npc/male01/vquestion06.wav", "vo/npc/female01/vquestion06.wav");
PLUGIN.voices:AddCitizen("Citizen", "Pals with vort", "If anyone ever told me I'd be pals with a vortigaunt.", "vo/npc/male01/vquestion07.wav", "vo/npc/female01/vquestion07.wav");

-- Human = working voices
PLUGIN.voices:AddCitizen("Human", "You all over", "That's you all over.", "vo/npc/male01/answer01.wav", "vo/npc/female01/answer01.wav");
PLUGIN.voices:AddCitizen("Human", "Hold it against you", "I won't hold it against you.", "vo/npc/male01/answer02.wav", "vo/npc/female01/answer02.wav");
PLUGIN.voices:AddCitizen("Human", "Figures", "Figures.", "vo/npc/male01/answer03.wav", "vo/npc/female01/answer03.wav");
PLUGIN.voices:AddCitizen("Human", "Dwell on it", "Try not to dwell on it.", "vo/npc/male01/answer04.wav", "vo/npc/female01/answer04.wav");
PLUGIN.voices:AddCitizen("Human", "Talk later", "Can we talk about this later?", "vo/npc/male01/answer05.wav", "vo/npc/female01/answer05.wav");
PLUGIN.voices:AddCitizen("Human", "Same here", "Same here.", "vo/npc/male01/answer07.wav", "vo/npc/female01/answer07.wav");
PLUGIN.voices:AddCitizen("Human", "Know what you mean", "Know what you mean.", "vo/npc/male01/answer08.wav", "vo/npc/female01/answer08.wav");
PLUGIN.voices:AddCitizen("Human", "Talking to yourself", "Talking to yourself again.", "vo/npc/male01/answer09.wav", "vo/npc/female01/answer09.wav");
PLUGIN.voices:AddCitizen("Human", "Say that too loud", "I wouldn't say that too loud.", "vo/npc/male01/answer10.wav", "vo/npc/female01/answer10.wav");
PLUGIN.voices:AddCitizen("Human", "Tomb stone", "I'll put it on your tomb stone.", "vo/npc/male01/answer11.wav", "vo/npc/female01/answer11.wav");
PLUGIN.voices:AddCitizen("Human", "Thinking about", "Doesn't bare thinking about.", "vo/npc/male01/answer12.wav", "vo/npc/female01/answer12.wav");
PLUGIN.voices:AddCitizen("Human", "With you", "I'm with you.", "vo/npc/male01/answer13.wav", "vo/npc/female01/answer13.wav");
PLUGIN.voices:AddCitizen("Human", "You and me both", "You and me both.", "vo/npc/male01/answer14.wav", "vo/npc/female01/answer14.wav");
PLUGIN.voices:AddCitizen("Human", "looking at it", "That's one way of looking at it.", "vo/npc/male01/answer15.wav", "vo/npc/female01/answer15.wav");
PLUGIN.voices:AddCitizen("Human", "Original Thought", "Have you ever had an original thought?", "vo/npc/male01/answer16.wav", "vo/npc/female01/answer16.wav");
PLUGIN.voices:AddCitizen("Human", "Shut up", "I'm not even going to tell you to shut up.", "vo/npc/male01/answer17.wav", "vo/npc/female01/answer17.wav");
PLUGIN.voices:AddCitizen("Human", "Task at hand", "Let's concentrate on the task at hand.", "vo/npc/male01/answer18.wav", "vo/npc/female01/answer18.wav");
PLUGIN.voices:AddCitizen("Human", "Mind on work", "Keep your mind on your work.", "vo/npc/male01/answer19.wav", "vo/npc/female01/answer19.wav");
PLUGIN.voices:AddCitizen("Human", "Mind in gutter", "Your mind is in the gutter.", "vo/npc/male01/answer20.wav", "vo/npc/female01/answer20.wav");
PLUGIN.voices:AddCitizen("Human", "Sure of that", "Don't be so sure of that.", "vo/npc/male01/answer21.wav", "vo/npc/female01/answer21.wav");
PLUGIN.voices:AddCitizen("Human", "Never know", "You never know.", "vo/npc/male01/answer22.wav", "vo/npc/female01/answer22.wav");
PLUGIN.voices:AddCitizen("Human", "Never can tell", "Never can tell.", "vo/npc/male01/answer23.wav", "vo/npc/female01/answer23.wav");
PLUGIN.voices:AddCitizen("Human", "Why telling me", "Why are you telling me?", "vo/npc/male01/answer24.wav", "vo/npc/female01/answer24.wav");
PLUGIN.voices:AddCitizen("Human", "How about that", "How about that.", "vo/npc/male01/answer25.wav", "vo/npc/female01/answer25.wav");
PLUGIN.voices:AddCitizen("Human", "More information", "That's more information than I require.", "vo/npc/male01/answer26.wav", "vo/npc/female01/answer26.wav");
PLUGIN.voices:AddCitizen("Human", "Wannna bet", "Wanna bet?", "vo/npc/male01/answer27.wav", "vo/npc/female01/answer27.wav");
PLUGIN.voices:AddCitizen("Human", "A dime", "I wish I had a dime for everytime somebody said that.", "vo/npc/male01/answer28.wav", "vo/npc/female01/answer28.wav");
PLUGIN.voices:AddCitizen("Human", "Do about it", "What am I supposed to do about it?", "vo/npc/male01/answer29.wav", "vo/npc/female01/answer29.wav");
PLUGIN.voices:AddCitizen("Human", "Talking to me", "You talking to me?", "vo/npc/male01/answer30.wav", "vo/npc/female01/answer30.wav");
PLUGIN.voices:AddCitizen("Human", "Nip that talk", "You should nip that kind of talk in the bud.", "vo/npc/male01/answer31.wav", "vo/npc/female01/answer31.wav");
PLUGIN.voices:AddCitizen("Human", "Right on", "Right on.", "vo/npc/male01/answer32.wav", "vo/npc/female01/answer32.wav");
PLUGIN.voices:AddCitizen("Human", "No argument", "No argument there.", "vo/npc/male01/answer33.wav", "vo/npc/female01/answer33.wav");
PLUGIN.voices:AddCitizen("Human", "Hawaii", "Don't forget hawaii.", "vo/npc/male01/answer34.wav", "vo/npc/female01/answer34.wav");
PLUGIN.voices:AddCitizen("Human", "Let it get to you", "Try not to let it get to you.", "vo/npc/male01/answer35.wav", "vo/npc/female01/answer36.wav");
PLUGIN.voices:AddCitizen("Human", "First time", "Wouldn't be the first time.", "vo/npc/male01/answer36.wav", "vo/npc/female01/answer37.wav");
PLUGIN.voices:AddCitizen("Human", "Sure about that", "You sure about that?", "vo/npc/male01/answer37.wav", "vo/npc/female01/answer38.wav");
PLUGIN.voices:AddCitizen("Human", "Leave it alone", "Leave it alone.", "vo/npc/male01/answer38.wav", "vo/npc/female01/answer39.wav");
PLUGIN.voices:AddCitizen("Human", "Enough out of you", "That's enough out of you.", "vo/npc/male01/answer39.wav", "vo/npc/female01/answer40.wav");
PLUGIN.voices:AddCitizen("Human", "Talking to me", "You talking to me?", "vo/npc/male01/answer30.wav", "vo/npc/female01/answer30.wav");
PLUGIN.voices:AddCitizen("Human", "Remember anything", "I can't remember the last time I had, well... Anything.", "vo/npc/male01/question31.wav", "vo/npc/female01/answer35.wav");
PLUGIN.voices:AddCitizen("Human", "Wars gonna end", "I don't think this wars ever gonna end.", "vo/npc/male01/question01.wav", "vo/npc/female01/question01.wav");
PLUGIN.voices:AddCitizen("Human", "Sell insurance", "To think, all I used to wanna do is sell insurance.", "vo/npc/male01/question02.wav", "vo/npc/female01/question02.wav");
PLUGIN.voices:AddCitizen("Human", "Dream anymore", "I don't dream anymore.", "vo/npc/male01/question03.wav", "vo/npc/female01/question03.wav");
PLUGIN.voices:AddCitizen("Human", "All over kidding", "When this is all over I'm... Ah who am I kidding.", "vo/npc/male01/question04.wav", "vo/npc/female01/question04.wav");
PLUGIN.voices:AddCitizen("Human", "Deja vu", "Woah, Deja vu.", "vo/npc/male01/question05.wav", "vo/npc/female01/question05.wav");
PLUGIN.voices:AddCitizen("Human", "Dream about cheese", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav", "vo/npc/female01/question06.wav");
PLUGIN.voices:AddCitizen("Human", "Smell freedom", "You smell that? It's freedom.", "vo/npc/male01/question07.wav", "vo/npc/female01/question07.wav");
PLUGIN.voices:AddCitizen("Human", "Hands on doctor breen", "If I ever get my hands on Doctor Breen.", "vo/npc/male01/question08.wav", "vo/npc/female01/question08.wav");
PLUGIN.voices:AddCitizen("Human", "Eat a horse", "I could eat a horse, hooves and all.", "vo/npc/male01/question09.wav", "vo/npc/female01/question09.wav");
PLUGIN.voices:AddCitizen("Human", "Day finally come", "I can't believe this day has finally come.", "vo/npc/male01/question10.wav", "vo/npc/female01/question10.wav");
PLUGIN.voices:AddCitizen("Human", "Not part of plan", "I'm pretty sure this isn't part of the plan.", "vo/npc/male01/question11.wav", "vo/npc/female01/question11.wav");
PLUGIN.voices:AddCitizen("Human", "Getting worse", "Looks to me things are getting worse, not better.", "vo/npc/male01/question12.wav", "vo/npc/female01/question12.wav");
PLUGIN.voices:AddCitizen("Human", "Live my life over", "If I could live my life over again.", "vo/npc/male01/question13.wav", "vo/npc/female01/question13.wav");
PLUGIN.voices:AddCitizen("Human", "Reminds me of", "I'm not even going to tell you what that reminds me of.", "vo/npc/male01/question14.wav", "vo/npc/female01/question14.wav");
PLUGIN.voices:AddCitizen("Human", "Stalker out of me", "They're never going to make a stalker out of me.", "vo/npc/male01/question15.wav", "vo/npc/female01/question15.wav");
PLUGIN.voices:AddCitizen("Human", "Change in air", "Finally, change is in the air.", "vo/npc/male01/question16.wav", "vo/npc/female01/question16.wav");
PLUGIN.voices:AddCitizen("Human", "You feel it", "You feel it? I feel it.", "vo/npc/male01/question17.wav", "vo/npc/female01/question17.wav");
PLUGIN.voices:AddCitizen("Human", "Dont feel anything", "I don't feel anything anymore.", "vo/npc/male01/question18.wav", "vo/npc/female01/question18.wav");
PLUGIN.voices:AddCitizen("Human", "Last shower", "I can't remember the last time I had a shower.", "vo/npc/male01/question19.wav", "vo/npc/female01/question19.wav");
PLUGIN.voices:AddCitizen("Human", "Bad memory", "Someday, this will all be a bad memory.", "vo/npc/male01/question20.wav", "vo/npc/female01/question20.wav");
PLUGIN.voices:AddCitizen("Human", "Betting man", "I'm not a betting man, but the odds are not good.", "vo/npc/male01/question21.wav", "vo/npc/female01/question21.wav");
PLUGIN.voices:AddCitizen("Human", "Care what i think", "Doesn't anyone care what I think?", "vo/npc/male01/question22.wav", "vo/npc/female01/question22.wav");
PLUGIN.voices:AddCitizen("Human", "Whistle tune", "I can't get this tune out of my head. *Whistling*", "vo/npc/male01/question23.wav", "vo/npc/female01/question23.wav");
PLUGIN.voices:AddCitizen("Human", "One of those days", "I just knew it was going to be one of those days.", "vo/npc/male01/question25.wav", "vo/npc/female01/question25.wav");
PLUGIN.voices:AddCitizen("Human", "Bullshit", "This is bullshit!", "vo/npc/male01/question26.wav", "vo/npc/female01/question26.wav");
PLUGIN.voices:AddCitizen("Human", "Ate something bad", "I think I ate something bad.", "vo/npc/male01/question27.wav", "vo/npc/female01/question27.wav");
PLUGIN.voices:AddCitizen("Human", "Im hungry", "God I'm hungry.", "vo/npc/male01/question28.wav", "vo/npc/female01/question28.wav");
PLUGIN.voices:AddCitizen("Human", "Gonna mate", "When this is all over, I'm gonna mate.", "vo/npc/male01/question29.wav", "vo/npc/female01/question29.wav");
PLUGIN.voices:AddCitizen("Human", "No kids", "I'm glad there's no kids around to see this.", "vo/npc/male01/question30.wav", "vo/npc/female01/question30.wav");
PLUGIN.voices:AddCitizen("Human", "Behind you", "Behind you!", "vo/npc/male01/behindyou01.wav", "vo/npc/female01/behindyou01.wav");
PLUGIN.voices:AddCitizen("Human", "Im busy", "Can't you see I'm busy?", "vo/npc/male01/busy02.wav", "vo/npc/female01/busy02.wav");
PLUGIN.voices:AddCitizen("Human", "Look out below", "Look out below!", "vo/npc/male01/cit_dropper04.wav", "vo/npc/female01/cit_dropper04.wav");
PLUGIN.voices:AddCitizen("Human", "Civil protection", "Civil protection!", "vo/npc/male01/civilprotection01.wav", "vo/npc/female01/civilprotection01.wav");
PLUGIN.voices:AddCitizen("Human", "Combine", "Combine!", "vo/npc/male01/combine01.wav", "vo/npc/female01/combine01.wav");
PLUGIN.voices:AddCitizen("Human", "Cps", "Cps!", "vo/npc/male01/cps01.wav", "vo/npc/female01/cps01.wav");
PLUGIN.voices:AddCitizen("Human", "Cover reload", "Cover me while I reload.", "vo/npc/male01/coverwhilereload01.wav", "vo/npc/female01/coverwhilereload01.wav");
PLUGIN.voices:AddCitizen("Human", "Doing something", "Shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav", "vo/npc/female01/doingsomething.wav");
PLUGIN.voices:AddCitizen("Human", "Excuse me", "Excuse me.", "vo/npc/male01/excuseme01.wav", "vo/npc/female01/excuseme01.wav");
PLUGIN.voices:AddCitizen("Human", "Fantastic", "Fantastic!", "vo/npc/male01/fantastic01.wav", "vo/npc/female01/fantastic01.wav");
PLUGIN.voices:AddCitizen("Human", "Finally", "Finally.", "vo/npc/male01/finally.wav", "vo/npc/female01/finally.wav");
PLUGIN.voices:AddCitizen("Human", "Get down", "Get down!", "vo/npc/male01/getdown02.wav", "vo/npc/female01/getdown02.wav");
PLUGIN.voices:AddCitizen("Human", "Get going soon", "Are we gonna get going soon?", "vo/npc/male01/getgoingsoon.wav", "vo/npc/female01/getgoingsoon.wav");
PLUGIN.voices:AddCitizen("Human", "Get the hell out", "Get the hell out of here!", "vo/npc/male01/gethellout.wav", "vo/npc/female01/gethellout.wav");
PLUGIN.voices:AddCitizen("Human", "Good god", "Good god.", "vo/npc/male01/goodgod.wav", "vo/npc/female01/goodgod.wav");
PLUGIN.voices:AddCitizen("Human", "Now what", "Now what.", "vo/npc/male01/gordead_ans01.wav", "vo/npc/female01/gordead_ans01.wav");
PLUGIN.voices:AddCitizen("Human", "Going so well", "And things were going so well.", "vo/npc/male01/gordead_ans02.wav", "vo/npc/female01/gordead_ans02.wav");
PLUGIN.voices:AddCitizen("Human", "Dont tell me", "Don't tell me.", "vo/npc/male01/gordead_ans03.wav", "vo/npc/female01/gordead_ans03.wav");
PLUGIN.voices:AddCitizen("Human", "Oh god", "Oh god.", "vo/npc/male01/gordead_ans04.wav", "vo/npc/female01/gordead_ans04.wav");
PLUGIN.voices:AddCitizen("Human", "Oh no", "Oh no.", "vo/npc/male01/gordead_ans05.wav", "vo/npc/female01/gordead_ans05.wav");
PLUGIN.voices:AddCitizen("Human", "Please no", "Please no!", "vo/npc/male01/gordead_ans06.wav", "vo/npc/female01/gordead_ans06.wav");
PLUGIN.voices:AddCitizen("Human", "Thats gotta hurt", "If you dare say... that's gotta hurt, I'll kill you.", "vo/npc/male01/gordead_ans07.wav", "vo/npc/female01/gordead_ans07.wav");
PLUGIN.voices:AddCitizen("Human", "Bury him here", "Should we bury him here?", "vo/npc/male01/gordead_ans08.wav", "vo/npc/female01/gordead_ans08.wav");
PLUGIN.voices:AddCitizen("Human", "Even he could not help", "I had a feeling even he couldn't help us.", "vo/npc/male01/gordead_ans09.wav", "vo/npc/female01/gordead_ans09.wav");
PLUGIN.voices:AddCitizen("Human", "Spread the word", "Spread the word.", "vo/npc/male01/gordead_ans10.wav", "vo/npc/female01/gordead_ans10.wav");
PLUGIN.voices:AddCitizen("Human", "What is the use", "What's the use?", "vo/npc/male01/gordead_ans11.wav", "vo/npc/female01/gordead_ans11.wav");
PLUGIN.voices:AddCitizen("Human", "What is the point", "What's the point?", "vo/npc/male01/gordead_ans12.wav", "vo/npc/female01/gordead_ans12.wav");
PLUGIN.voices:AddCitizen("Human", "Why go on", "Why go on?", "vo/npc/male01/gordead_ans13.wav", "vo/npc/female01/gordead_ans13.wav");
PLUGIN.voices:AddCitizen("Human", "Were done for", "We're done for.", "vo/npc/male01/gordead_ans14.wav", "vo/npc/female01/gordead_ans14.wav");
PLUGIN.voices:AddCitizen("Human", "Well now what", "Well, now what?", "vo/npc/male01/gordead_ans15.wav", "vo/npc/female01/gordead_ans15.wav");
PLUGIN.voices:AddCitizen("Human", "Dibs on the suit", "Dibs on the suit!", "vo/npc/male01/gordead_ans16.wav", "vo/npc/female01/gordead_ans16.wav");
PLUGIN.voices:AddCitizen("Human", "Done this before", "He's done this before, he'll be okay.", "vo/npc/male01/gordead_ans18.wav", "vo/npc/female01/gordead_ans18.wav");
PLUGIN.voices:AddCitizen("Human", "Gonna be sick", "I'm gonna be sick.", "vo/npc/male01/gordead_ans19.wav", "vo/npc/female01/gordead_ans19.wav");
PLUGIN.voices:AddCitizen("Human", "Take his crowbar", "Somebody, take his crowbar.", "vo/npc/male01/gordead_ans20.wav", "vo/npc/female01/gordead_ans20.wav");
PLUGIN.voices:AddCitizen("Human", "Hes dead", "He's dead.", "vo/npc/male01/gordead_ques01.wav", "vo/npc/female01/gordead_ques01.wav");
PLUGIN.voices:AddCitizen("Human", "Way to go", "What a way to go.", "vo/npc/male01/gordead_ques02.wav", "vo/npc/female01/gordead_ques02.wav");
PLUGIN.voices:AddCitizen("Human", "Cant be", "This can't be.", "vo/npc/male01/gordead_ques06.wav", "vo/npc/female01/gordead_ques06.wav");
PLUGIN.voices:AddCitizen("Human", "Look hes dead", "Look he's dead.", "vo/npc/male01/gordead_ques07.wav", "vo/npc/female01/gordead_ques07.wav");
PLUGIN.voices:AddCitizen("Human", "This is bad", "This, is bad.", "vo/npc/male01/gordead_ques10.wav", "vo/npc/female01/gordead_ques10.wav");
PLUGIN.voices:AddCitizen("Human", "End like this", "It's not supposed to end like this.", "vo/npc/male01/gordead_ques14.wav", "vo/npc/female01/gordead_ques14.wav");
PLUGIN.voices:AddCitizen("Human", "What now", "What now?", "vo/npc/male01/gordead_ques16.wav", "vo/npc/female01/gordead_ques16.wav");
PLUGIN.voices:AddCitizen("Human", "Got one", "Got one!", "vo/npc/male01/gotone01.wav", "vo/npc/female01/gotone01.wav");
PLUGIN.voices:AddCitizen("Human", "Gotta reload", "Gotta reload.", "vo/npc/male01/gottareload01.wav", "vo/npc/female01/gottareload01.wav");
PLUGIN.voices:AddCitizen("Human", "Hacks", "Hacks!", "vo/npc/male01/hacks01.wav", "vo/npc/female01/hacks01.wav");
PLUGIN.voices:AddCitizen("Human", "Headcrabs", "Headcrabs!", "vo/npc/male01/headcrabs01.wav", "vo/npc/female01/headcrabs01.wav");
PLUGIN.voices:AddCitizen("Human", "Heads up", "Heads up!", "vo/npc/male01/headsup01.wav", "vo/npc/female01/headsup01.wav");
PLUGIN.voices:AddCitizen("Human", "Help", "Help!", "vo/npc/male01/help01.wav", "vo/npc/female01/help01.wav");
PLUGIN.voices:AddCitizen("Human", "Here come hacks", "Here come the hacks!", "vo/npc/male01/herecomehacks01.wav", "vo/npc/female01/herecomehacks01.wav");
PLUGIN.voices:AddCitizen("Human", "Here they come", "Here they come!", "vo/npc/male01/heretheycome01.wav", "vo/npc/female01/heretheycome01.wav");
PLUGIN.voices:AddCitizen("Human", "Here to help", "We thought you were here to help.", "vo/npc/male01/heretohelp01.wav", "vo/npc/female01/heretohelp01.wav");
PLUGIN.voices:AddCitizen("Human", "Hi", "Hi.", "vo/npc/male01/hi01.wav", "vo/npc/female01/hi01.wav");
PLUGIN.voices:AddCitizen("Human", "Hit in gut", "Aargh, hit in the gut.", "vo/npc/male01/hitingut01.wav", "vo/npc/female01/hitingut01.wav");
PLUGIN.voices:AddCitizen("Human", "Hold this spot", "I'm gonna stay here and hold down this spot.", "vo/npc/male01/holddownspot01.wav", "vo/npc/female01/holddownspot01.wav");
PLUGIN.voices:AddCitizen("Human", "Ill stay here", "I'll stay here", "vo/npc/male01/illstayhere01.wav", "vo/npc/female01/illstayhere01.wav");
PLUGIN.voices:AddCitizen("Human", "Im hurt", "Aargh, I'm hurt.", "vo/npc/male01/imhurt01.wav", "vo/npc/female01/imhurt01.wav");
PLUGIN.voices:AddCitizen("Human", "Sticking here", "I'm sticking here.", "vo/npc/male01/imstickinghere01.wav", "vo/npc/female01/imstickinghere01.wav");
PLUGIN.voices:AddCitizen("Human", "Incoming", "Incoming!", "vo/npc/male01/incoming02.wav", "vo/npc/female01/incoming02.wav");
PLUGIN.voices:AddCitizen("Human", "Lead the way", "You lead the way!", "vo/npc/male01/leadtheway01.wav", "vo/npc/female01/leadtheway01.wav");
PLUGIN.voices:AddCitizen("Human", "Lets go", "Lets go.", "vo/npc/male01/letsgo02.wav", "vo/npc/female01/letsgo02.wav");
PLUGIN.voices:AddCitizen("Human", "My arm", "Aargh, my arm.", "vo/npc/male01/myarm01.wav", "vo/npc/female01/myarm01.wav");
PLUGIN.voices:AddCitizen("Human", "My leg", "Aargh, my leg.", "vo/npc/male01/myleg01.wav", "vo/npc/female01/myleg01.wav");
PLUGIN.voices:AddCitizen("Human", "Nice", "Nice!", "vo/npc/male01/nice.wav", "vo/npc/female01/nice02.wav");
PLUGIN.voices:AddCitizen("Human", "Noooo", "Nooooo!", "vo/npc/male01/no02.wav", "vo/npc/female01/no02.wav");
PLUGIN.voices:AddCitizen("Human", "Man I thought", "You're not the man I thought you were.", "vo/npc/male01/notthemanithought02.wav", "vo/npc/female01/notthemanithought02.wav");
PLUGIN.voices:AddCitizen("Human", "Oh no", "Oh no.", "vo/npc/male01/ohno.wav", "vo/npc/female01/ohno.wav");
PLUGIN.voices:AddCitizen("Human", "Okay", "Okay!", "vo/npc/male01/ok01.wav", "vo/npc/female01/ok01.wav");
PLUGIN.voices:AddCitizen("Human", "Im ready", "Okay, I'm ready.", "vo/npc/male01/okimready01.wav", "vo/npc/female01/okimready01.wav");
PLUGIN.voices:AddCitizen("Human", "Get out of way", "Let me get out of your way.", "vo/npc/male01/outofyourway02.wav", "vo/npc/female01/outofyourway02.wav");
PLUGIN.voices:AddCitizen("Human", "Over here", "Over here!", "vo/npc/male01/overhere01.wav", "vo/npc/female01/overhere01.wav");
PLUGIN.voices:AddCitizen("Human", "Over there", "Over there!", "vo/npc/male01/overthere01.wav", "vo/npc/female01/overthere01.wav");
PLUGIN.voices:AddCitizen("Human", "Pardon me", "Pardon me.", "vo/npc/male01/pardonme02.wav", "vo/npc/female01/pardonme02.wav");
PLUGIN.voices:AddCitizen("Human", "Ready when you are", "Ready when you are!", "vo/npc/male01/readywhenyouare01.wav", "vo/npc/female01/readywhenyouare01.wav");
PLUGIN.voices:AddCitizen("Human", "Run for your life", "Run for your life!", "vo/npc/male01/runforyourlife02.wav", "vo/npc/female01/runforyourlife02.wav");
PLUGIN.voices:AddCitizen("Human", "Sorry", "Sorry.", "vo/npc/male01/sorry03.wav", "vo/npc/female01/sorry03.wav");
PLUGIN.voices:AddCitizen("Human", "Follow me", "Follow me!", "vo/npc/male01/squad_away03.wav", "vo/npc/female01/squad_away03.wav");
PLUGIN.voices:AddCitizen("Human", "Tale cover", "Take cover.", "vo/npc/male01/takecover02.wav", "vo/npc/female01/takecover02.wav");
PLUGIN.voices:AddCitizen("Human", "Do nicely", "This will do nicely.", "vo/npc/male01/thislldonicely01.wav", "vo/npc/female01/thislldonicely01.wav");
PLUGIN.voices:AddCitizen("Human", "Uh oh", "Uh oh!", "vo/npc/male01/uhoh.wav", "vo/npc/female01/uhoh.wav");
PLUGIN.voices:AddCitizen("Human", "Up there", "Up there!", "vo/npc/male01/upthere01.wav", "vo/npc/female01/upthere01.wav");
PLUGIN.voices:AddCitizen("Human", "Waiting for somebody", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav", "vo/npc/female01/waitingsomebody.wav");
PLUGIN.voices:AddCitizen("Human", "Watch out", "Watch out!", "vo/npc/male01/watchout.wav", "vo/npc/female01/watchout.wav");
PLUGIN.voices:AddCitizen("Human", "Watch what doing", "Watch what you're doing!", "vo/npc/male01/watchwhat.wav", "vo/npc/female01/watchwhat.wav");
PLUGIN.voices:AddCitizen("Human", "We trusted you", "We trusted you!", "vo/npc/male01/wetrustedyou01.wav", "vo/npc/female01/wetrustedyou01.wav");
PLUGIN.voices:AddCitizen("Human", "Woops", "Woops.", "vo/npc/male01/whoops01.wav", "vo/npc/female01/whoops01.wav");
PLUGIN.voices:AddCitizen("Human", "Yeah", "Yeah.", "vo/npc/male01/yeah02.wav", "vo/npc/female01/yeah02.wav");
PLUGIN.voices:AddCitizen("Human", "You reload", "You'd better reload.", "vo/npc/male01/youdbetterreload01.wav", "vo/npc/female01/youdbetterreload01.wav");
PLUGIN.voices:AddCitizen("Human", "You got it", "You got it.", "vo/npc/male01/yougotit02.wav", "vo/npc/female01/yougotit02.wav");
PLUGIN.voices:AddCitizen("Human", "Zombies", "Zombies!", "vo/npc/male01/zombies01.wav", "vo/npc/female01/zombies01.wav");
PLUGIN.voices:AddCitizen("Human", "Woops", "Woops.", "vo/npc/male01/whoops01.wav", "vo/npc/female01/whoops01.wav");
PLUGIN.voices:AddCitizen("Human", "Mumbo jumbo", "Enough of your mumbo jumbo.", "vo/npc/male01/vanswer01.wav", "vo/npc/female01/vanswer01.wav");
PLUGIN.voices:AddCitizen("Human", "Damn vorts", "Damn vorts.", "vo/npc/male01/vanswer02.wav", "vo/npc/female01/vanswer02.wav");
PLUGIN.voices:AddCitizen("Human", "How to take that", "I'm not sure how to take that.", "vo/npc/male01/vanswer03.wav", "vo/npc/female01/vanswer03.wav");
PLUGIN.voices:AddCitizen("Human", "Take that personally", "Should I take that personally?", "vo/npc/male01/vanswer04.wav", "vo/npc/female01/vanswer04.wav");
PLUGIN.voices:AddCitizen("Human", "Speak english", "Speak english.", "vo/npc/male01/vanswer05.wav", "vo/npc/female01/vanswer05.wav");
PLUGIN.voices:AddCitizen("Human", "Got that from me", "You got that from me!", "vo/npc/male01/vanswer06.wav", "vo/npc/female01/vanswer06.wav");
PLUGIN.voices:AddCitizen("Human", "Put up with you", "That's why we put up with you.", "vo/npc/male01/vanswer07.wav", "vo/npc/female01/vanswer07.wav");
PLUGIN.voices:AddCitizen("Human", "Put it better myself", "Couldn't have put it better myself.", "vo/npc/male01/vanswer08.wav", "vo/npc/female01/vanswer08.wav");
PLUGIN.voices:AddCitizen("Human", "Almost made sense", "That, almost made sense.", "vo/npc/male01/vanswer09.wav", "vo/npc/female01/vanswer09.wav");
PLUGIN.voices:AddCitizen("Human", "Something wrong with me", "Something must be wrong with me, I almost understood that.", "vo/npc/male01/vanswer10.wav", "vo/npc/female01/vanswer10.wav");
PLUGIN.voices:AddCitizen("Human", "Getting used to vorts", "I guess I'm getting used to you vorts.", "vo/npc/male01/vanswer11.wav", "vo/npc/female01/vanswer11.wav");
PLUGIN.voices:AddCitizen("Human", "Vort philosophy", "None of your vort philosophy.", "vo/npc/male01/vanswer12.wav", "vo/npc/female01/vanswer12.wav");
PLUGIN.voices:AddCitizen("Human", "Stop killing me", "Stop you're killing me.", "vo/npc/male01/vanswer13.wav", "vo/npc/female01/vanswer13.wav");
PLUGIN.voices:AddCitizen("Human", "Do to deserve this", "What did I do to deserve this.", "vo/npc/male01/vanswer14.wav", "vo/npc/female01/vanswer14.wav");
PLUGIN.voices:AddCitizen("Human", "Stop looking at me", "Stop looking at me like that.", "vo/npc/male01/vquestion01.wav", "vo/npc/female01/vquestion01.wav");
PLUGIN.voices:AddCitizen("Human", "Never get used to", "Some things I just never get used to.", "vo/npc/male01/vquestion02.wav", "vo/npc/female01/vquestion02.wav");
PLUGIN.voices:AddCitizen("Human", "Survived this long", "I don't know how you things have survived as long as you have.", "vo/npc/male01/vquestion03.wav", "vo/npc/female01/vquestion03.wav");
PLUGIN.voices:AddCitizen("Human", "Ended up with you", "Sometimes I wonder how I ended up with you.", "vo/npc/male01/vquestion04.wav", "vo/npc/female01/vquestion04.wav");
PLUGIN.voices:AddCitizen("Human", "Alright vorty", "You're alright vorty.", "vo/npc/male01/vquestion05.wav", "vo/npc/female01/vquestion05.wav");
PLUGIN.voices:AddCitizen("Human", "Vorts half bad", "You vorts aren't half bad.", "vo/npc/male01/vquestion06.wav", "vo/npc/female01/vquestion06.wav");
PLUGIN.voices:AddCitizen("Human", "Pals with vort", "If anyone ever told me I'd be pals with a vortigaunt.", "vo/npc/male01/vquestion07.wav", "vo/npc/female01/vquestion07.wav");

if (CLIENT) then
	table.sort(PLUGIN.voices.stored.citizenVoices, function(a, b) return a.command < b.command; end);
	
	for k, v in pairs(PLUGIN.voices.stored.citizenVoices) do
		Clockwork.directory:AddCode("Люди", [[
			<div class="auraInfoTitle">]]..string.upper(v.command)..[[</div>
			<div class="auraInfoText">]]..v.phrase..[[</div>
		]], true);
	end;
end;